@startuml Paquetes
package "Modelo" {
    class Plato {
        - ID_Plato: int
        - Nombre: string
        - Descripción: string
        - Precio: decimal
        - Foto: string
    }

    class Detalle_Orden {
        - ID_Detalle: int
        - ID_Orden: int
        - ID_Plato: int
        - Cantidad: int
        - Sopa: boolean
        - Postre: boolean
        - Domicilio: boolean
        - Recipiente: boolean
    }

    class Orden {
        - ID_Orden: int
        - ID_Mesa: int
        - HoraPedido: datetime
        - Total: decimal
    }

    class Mesa {
        - ID_Mesa: int
        - Numero_Mesa: int
        - Capacidad: int
        - Estado: string
    }

    class Usuario {
        - ID_Usuario: int
        - Nombre: string
        - Teléfono: string
        - Dirección: string
    }

    class Factura {
        - ID_Factura: int
        - ID_Orden: int
        - Fecha: date
        - Total: decimal
        - MetodoPago: string
    }
}

package "Servicios" {
    class PlatoService
    class OrdenService
    class DetalleOrdenService
    class UsuarioService
    class FacturaService
}

package "Base de Datos" {
    class Database
}

"Modelo" --> "Servicios" : utiliza >
"Servicios" --> "Base de Datos" : accede a >
"Modelo" --> "Base de Datos" : almacena datos en >

@enduml

